[package]
name = "bdk-esplora-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bdk = { git = "https://github.com/bitcoindevkit/bdk", rev = "2867e88b64b4a8cf7136cc562ec61c077737a087", default-features = false, features = ["compiler", "dev-getrandom-wasm", "std"] }
bdk_esplora = { git = "https://github.com/bitcoindevkit/bdk", rev = "2867e88b64b4a8cf7136cc562ec61c077737a087", default-features = false, features = ["async-https", "std"] }
once_cell = "1.18"
serde = "=1.0.171"
tokio = { version = "1", features = ["full"] }